package:
  name: nestedtensor
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
 path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    - {{ compiler('c') }} # [win]
    - libpng
    - jpeg

  host:
    - python
    - setuptools
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    {{ environ.get('CONDA_CPUONLY_FEATURE') }}

  run:
    - python
    - libpng
    - jpeg
    - pillow >=4.1.1
    - numpy >=1.11
    {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  string: py{{py}}_{{ environ['CU_VERSION'] }}
  script: >
    pushd third_party/pytorch
    python setup.py develop
    popd
    python setup.py install --single-version-externally-managed --record=record.txt # [not win]
  script_env:
    - CUDA_HOME
    - FORCE_CUDA
    - NVCC_FLAGS
    - BUILD_VERSION
  features:
    {{ environ.get('CONDA_CPUONLY_FEATURE') }}

test:
  imports:
    - nestedtensor
  source_files:
    - test
  requires:
    - pytest
    - scipy
    - av
    - ca-certificates
    {{ environ.get('CONDA_TYPING_CONSTRAINT') }}


about:
  home: https://github.com/pytorch/nestedtensor
  license: BSD
  license_file: LICENSE
  summary: 'Tools for the concurrent manipulation of variably sized Tensors.'
